services:
  # Full Stack Application (Backend + Frontend)
  - type: web
    name: lostandfound-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://kannanrushi05_db_user:V9HCHCbKVRB14uEq@cluster0.p2iuqpr.mongodb.net/web?retryWrites=true&w=majority&appName=Cluster0
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: https://lostandfound-app.onrender.com
